refactor: add PCSC_CPP_DISABLE_COPY_MOVE macro to implement The Rule of Five
web-eid/libpcsc-cpp pull request #26
Opened 2023-04-21 19:42 UTC by mrts

WE2-748

2023-04-24 06:57 UTC, metsma requested changes

2023-04-24 06:57 UTC, metsma commented on include/pcsc-cpp/disable-copy-move.hpp
Why separate file. Move to pcsc-cpp.hpp?

2023-04-30 13:46 UTC, mrts commented on include/pcsc-cpp/disable-copy-move.hpp
Not all modules that use the `PCSC_CPP_DISABLE_COPY_MOVE` macro include `pcsc-cpp.hpp`. It would be unwise to pollute their namespace with `pcsc-cpp.hpp` contents.

A prominent example is `src/electronic-ids/ms-cryptoapi/MsCryptoApiElectronicID.hpp` that has nothing to do with PC/SC, but requires `PCSC_CPP_DISABLE_COPY_MOVE`.

2023-04-30 17:25 UTC, metsma commented on include/pcsc-cpp/disable-copy-move.hpp
MsCryptoApiElectronicID.hpp Includes electronic-id.hpp and it has pcsc-cpp.hpp included there

2023-05-03 20:33 UTC, mrts commented on include/pcsc-cpp/disable-copy-move.hpp
Yes, my point was that it is not ideal that we include `pcsc-cpp.hpp` in `electronic-id.hpp`. But fair enough, I'll move `PCSC_CPP_DISABLE_COPY_MOVE` to `pcsc-cpp.hpp` for now.

2023-05-05 12:10 UTC, metsma approved these changes

2023-05-05 15:53 UTC, merged