Add byte_type
web-eid/libpcsc-cpp pull request #30
Opened 2023-06-24 16:26 UTC by mrts

WE2-751

2023-06-24 18:58 UTC, metsma requested changes

2023-06-24 18:58 UTC, metsma commented on include/pcsc-cpp/pcsc-cpp.hpp
> +using byte_type = byte_vector::value_type;
```suggestion
using byte_type = unsigned char;
using byte_vector = std::vector<byte_type>;
```

2023-06-26 07:57 UTC, mrts commented on include/pcsc-cpp/pcsc-cpp.hpp
> +using byte_type = byte_vector::value_type;
Thanks, fixed.

2023-06-26 07:58 UTC, metsma approved these changes

2023-06-26 08:03 UTC, merged